// <auto-generated />
using System;
using CarBrands.WebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarBrands.WebApi.Data.Migrations
{
    [DbContext(typeof(CarBrandsContext))]
    [Migration("20231222214910_dataSeed")]
    partial class dataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("CarBrands.WebApi.Domain.Entities.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("HeadquarterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slogan")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeadquarterId");

                    b.ToTable("CarBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateOnly(1931, 1, 1),
                            Description = "Dr. Ing. h.c. F. Porsche AG, usually shortened to Porsche,\r\n                                        is a German automobile manufacturer specializing in high-performance sports cars, SUVs and sedans",
                            HeadquarterId = 1,
                            Name = "Porsche",
                            Slogan = "There is no substitute."
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateOnly(1916, 3, 7),
                            Description = "The BMW Group is the world's leading provider of premium cars and motorcycles and the home of the BMW, MINI,\r\n                        Rolls-Royce and BMW Motorrad brands. Our vehicles and products are tailored to the needs of our customers and constantly enhanced –\r\n                        with a clear focus on sustainability and the conservation of resources.",
                            HeadquarterId = 2,
                            Name = "BMW",
                            Slogan = "Sheer Driving Pleasure"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateOnly(1927, 7, 28),
                            Description = "With Mercedes-Benz AG, we are one of the leading global suppliers of\r\n                        high-end passenger cars and premium vans.\r\n                                            Mercedes-Benz Mobility AG offers financing, leasing, car subscription and car rental,\r\n                        fleet management, digital services for charging and payment,\r\n                    insurance brokerage, as well as innovative mobility services.",
                            HeadquarterId = 3,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateOnly(1937, 5, 28),
                            Description = "The Volkswagen brand is one of the largest car manufacturers in the world. For more than 70 years,\r\n                        we have been making innovative technologies, the highest quality and attractive designs accessible to many people – with the likes \r\n                        of bestsellers such as the Beetle, the Golf and the all-electric ID.",
                            HeadquarterId = 4,
                            Name = "VW"
                        });
                });

            modelBuilder.Entity("CarBrands.WebApi.Domain.Entities.CarBrandCountryOfProduction", b =>
                {
                    b.Property<int>("CarBrandId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryOfProductionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CarBrandId", "CountryOfProductionId");

                    b.HasIndex("CountryOfProductionId");

                    b.ToTable("CarBrandCountryOfProduction");
                });

            modelBuilder.Entity("CarBrands.WebApi.Domain.Entities.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarBrandId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoupeType")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfDoors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProducedUnits")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarBrandId");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarBrandId = 1,
                            CoupeType = 2,
                            DateCreated = new DateOnly(2009, 4, 5),
                            Description = "The Porsche Panamera is a mid/full-sized luxury car (E-segment or F-segment for LWB in Europe) manufactured and marketed by German automobile manufacturer Porsche across two generations using a front-engine, rear or all-wheel drive configuration.",
                            Name = "Panamera",
                            NumberOfDoors = 4,
                            ProducedUnits = 30000
                        },
                        new
                        {
                            Id = 2,
                            CarBrandId = 1,
                            CoupeType = 11,
                            DateCreated = new DateOnly(2019, 7, 30),
                            Description = "The Porsche 911 (pronounced Nine Eleven or in German: Neunelf) is a two-door 2+2 high performance rear-engined sports car introduced in September 1964 by Porsche AG of Stuttgart, Germany. It has a rear-mounted flat-six engine and originally a torsion bar suspension.The car has been continuously enhanced through the years but the basic concept has remained unchanged.The engines were air-cooled until the introduction of the 996 series in 1998.",
                            Name = "911 - 992 Series",
                            NumberOfDoors = 2,
                            ProducedUnits = 10000
                        });
                });

            modelBuilder.Entity("CarBrands.WebApi.Domain.Entities.CountryOfProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISO3166Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CountriesOfProduction");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Germany is a country located in the heart of Western Europe. It is bordered by Denmark, Poland, Czechia, Austria, Switzerland, France, Luxembourg, Belgium, Netherlands, the North Sea, and the Baltic Sea. Germany has a strategic location on the North European Plain and along the entrance to the Baltic Sea.",
                            ISO3166Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Italy is a boot-shaped peninsula that juts out of southern Europe into the Adriatic Sea, Tyrrhenian Sea, Mediterranean Sea, and other waters. Its location has played an important role in its history.",
                            ISO3166Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 3,
                            Description = "France is one of the oldest nations on Earth and the most ethnically diverse country in Europe. These deep and broad influences have made France a world leader throughout history in nearly all aspects of culture, including cuisine, wine-making, politics, philosophy, music, art, film, fashion, literature, and sports.",
                            ISO3166Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The United Kingdom is a state made up of the historic countries of England, Wales and Scotland, as well as Northern Ireland. It is known as the home of both modern parliamentary democracy and the Industrial Revolution.",
                            ISO3166Code = "GB",
                            Name = "United Kingdom"
                        });
                });

            modelBuilder.Entity("CarBrands.WebApi.Domain.Entities.Headquarter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarBrandId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarBrandId");

                    b.ToTable("Headquarters");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Address = "Am Riesenfeld area of Munich",
                            CarBrandId = 0,
                            DateCreated = new DateOnly(1972, 1, 1),
                            Description = "The building has served as the global corporate headquarters of German automaker BMW since 1973. It was declared a protected historic building in 1999, and it is often cited as one of the most notable examples of modern architecture in Munich. Extensive renovations commenced in 2004 and were completed in 2006.",
                            Name = "BMW Tower"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Mercedesstraße 120\r\n70372 Stuttgart-Untertürkheim",
                            CarBrandId = 0,
                            DateCreated = new DateOnly(1926, 1, 1),
                            Description = "At the Headquarters of our international company at the location of Stuttgart, employees are working in various central functions and services and give the impetus for our way to a successful future.",
                            Name = "Mercedes-Benz Group Headquarters"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Berliner Ring 2, 38440 Wolfsburg",
                            CarBrandId = 0,
                            DateCreated = new DateOnly(1938, 1, 1),
                            Description = "No information is provided.",
                            Name = "Volkswagen Group Tower"
                        });
                });

            modelBuilder.Entity("CarBrands.WebApi.Domain.Entities.CarBrand", b =>
                {
                    b.HasOne("CarBrands.WebApi.Domain.Entities.Headquarter", "Headquarter")
                        .WithMany()
                        .HasForeignKey("HeadquarterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Headquarter");
                });

            modelBuilder.Entity("CarBrands.WebApi.Domain.Entities.CarBrandCountryOfProduction", b =>
                {
                    b.HasOne("CarBrands.WebApi.Domain.Entities.CarBrand", null)
                        .WithMany("CarBrandCountryOfProductions")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarBrands.WebApi.Domain.Entities.CountryOfProduction", null)
                        .WithMany("CarBrandCountryOfProductions")
                        .HasForeignKey("CountryOfProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarBrands.WebApi.Domain.Entities.CarModel", b =>
                {
                    b.HasOne("CarBrands.WebApi.Domain.Entities.CarBrand", "CarBrand")
                        .WithMany("CarModels")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarBrand");
                });

            modelBuilder.Entity("CarBrands.WebApi.Domain.Entities.Headquarter", b =>
                {
                    b.HasOne("CarBrands.WebApi.Domain.Entities.CarBrand", "CarBrand")
                        .WithMany()
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarBrand");
                });

            modelBuilder.Entity("CarBrands.WebApi.Domain.Entities.CarBrand", b =>
                {
                    b.Navigation("CarBrandCountryOfProductions");

                    b.Navigation("CarModels");
                });

            modelBuilder.Entity("CarBrands.WebApi.Domain.Entities.CountryOfProduction", b =>
                {
                    b.Navigation("CarBrandCountryOfProductions");
                });
#pragma warning restore 612, 618
        }
    }
}
